# -*- coding: utf-8 -*-
"""worldcup_2026_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NYVY4QLLHbEUUQfF8fDe3itMGORfuTBd
"""

# =============================================================================
# 2026 FIFA WORLD CUP MODEL -- single combined script (Parts 1, 2, 3, 3b)
# -----------------------------------------------------------------------------
# Paste this whole file into ONE Colab cell (with results.csv uploaded) and run.
# It fits the model, prints the ratings, and simulates the 2026 World Cup.
# For validation, then call:  backtest_matches()  and  backtest_stages()
#
# BEFORE TRUSTING RESULTS: fill the three PLAYOFF_* placeholders in GROUPS_2026
# and make team names match your dataset (the run prints any it can't find).
# =============================================================================

# =============================================================================
# 2026 FIFA World Cup model -- PART 1: ratings engine
# -----------------------------------------------------------------------------
# Runs on the Kaggle "International football results from 1872 to present"
# dataset (results.csv) ALONE. It produces:
#   * a cleaned, competition-weighted training set (friendlies excluded)
#   * your own Elo ratings (used both as a prior and as a baseline later)
#   * a weighted Dixon-Coles fit with a Gaussian prior that shrinks thin
#     teams toward their Elo strength
#   * a match predictor (1X2 probabilities + most likely scoreline)
#
# Part 2 (tournament Monte Carlo + backtesting) plugs into the `predict_match`
# output and additionally needs the 2026 group draw + third-place matrix.
#
# Paste this whole file into a single Google Colab cell (or upload as .py).
# =============================================================================

import numpy as np
import pandas as pd
from scipy.optimize import minimize
from scipy.special import gammaln
from scipy.stats import poisson

# -----------------------------------------------------------------------------
# CONFIG -- these are your hyperparameters. The starting values are sensible;
# in Part 2 you will TUNE them by backtesting rather than trust them blindly.
# -----------------------------------------------------------------------------
RESULTS_PATH    = "results.csv"   # path to the Kaggle file in your Colab session
TRAIN_YEARS_BACK = 12             # ignore matches older than this (squad drift)
HALF_LIFE_DAYS  = 900             # time-decay half-life (~2.5 years)
FRIENDLY_WEIGHT = 0.20            # friendlies kept as LOW-weight cross-confederation bridges
GOAL_CAP        = 5               # cap blowout scorelines so minnow-thrashings don't inflate attack
KAPPA           = 8.0             # strength of the Elo prior (higher = more shrinkage)
SIGMA_SCALE     = 0.55            # spread of Elo-implied strength on the log-goal scale
MAX_GOALS       = 10              # truncation for the scoreline matrix in prediction
RHO_BOUNDS      = (-0.2, 0.2)     # Dixon-Coles low-score dependence bound
HFA_ELO         = 65.0           # home-field advantage in Elo points (non-neutral only)
ELO_K           = 30.0           # base Elo K-factor
LN2             = np.log(2.0)

# -----------------------------------------------------------------------------
# 1. TEAM-NAME NORMALIZATION
#    The dataset splits some nations across historical / alternate spellings.
#    This is a STARTER map -- expand it as you spot duplicates in your data
#    (run df.home_team.unique() and eyeball it).
# -----------------------------------------------------------------------------
NAME_MAP = {
    "United States": "USA",
    "Republic of Ireland": "Ireland",
    "China PR": "China",
    "Korea Republic": "South Korea",
    "Korea DPR": "North Korea",
    "Czechoslovakia": "Czech Republic",   # debatable; merge or drop per taste
    "West Germany": "Germany",
    "Yugoslavia": "Serbia",               # debatable historical merge
    "Zaire": "DR Congo",
    "Cape Verde Islands": "Cape Verde",
}

def normalize_names(df):
    df = df.copy()
    for col in ("home_team", "away_team"):
        df[col] = df[col].replace(NAME_MAP)
    return df

# -----------------------------------------------------------------------------
# 2. COMPETITION IMPORTANCE TIERS (phi). Friendlies are kept at a LOW weight
#    because they are the main matches that BRIDGE confederations -- dropping
#    them leaves the model unable to calibrate (e.g.) Asia vs Europe.
#    Order matters: check 'qualification' before the finals keywords.
# -----------------------------------------------------------------------------
def competition_weight(tournament: str) -> float:
    t = tournament.lower()
    if "friendly" in t:
        return FRIENDLY_WEIGHT
    if "qualification" in t or "qualifier" in t:
        return 0.70
    if "nations league" in t:
        return 0.60
    if t == "fifa world cup" or "world cup" == t:
        return 1.00
    # continental finals tournaments
    finals_kw = ["uefa euro", "copa am", "africa cup", "african cup",
                 "afc asian cup", "gold cup", "concacaf championship",
                 "confederations cup", "copa america"]
    if any(k in t for k in finals_kw):
        return 0.90
    # any other competitive match (regional cups, etc.)
    return 0.50

# -----------------------------------------------------------------------------
# 3. DATA LOADING + COMPETITIVE FILTER + WEIGHTS
# -----------------------------------------------------------------------------
def load_and_prepare(path=RESULTS_PATH, as_of=None):
    df = pd.read_csv(path, parse_dates=["date"])
    df = normalize_names(df)

    if as_of is None:
        as_of = df["date"].max()          # default: predict "today"
    as_of = pd.Timestamp(as_of)

    # STRICT cutoff -- nothing on or after the prediction date may be used.
    df = df[df["date"] < as_of].copy()
    df = df[df["date"] >= as_of - pd.Timedelta(days=365 * TRAIN_YEARS_BACK)]

    df["phi"] = df["tournament"].apply(competition_weight)
    df = df[df["phi"] > 0].copy()          # keep everything with a positive weight

    # time decay anchored to the PREDICTION date (not "now")
    age_days = (as_of - df["date"]).dt.days.to_numpy()
    df["w"] = df["phi"].to_numpy() * np.exp(-LN2 * age_days / HALF_LIFE_DAYS)

    # normalize mean weight to 1 so effective N and prior strength are comparable
    df["w"] = df["w"] * len(df) / df["w"].sum()

    df = df.dropna(subset=["home_score", "away_score"])
    df["home_score"] = df["home_score"].astype(int)
    df["away_score"] = df["away_score"].astype(int)
    # cap blowouts: a 7-0 over a minnow shouldn't inflate attack more than a 5-0
    df["home_score"] = df["home_score"].clip(upper=GOAL_CAP)
    df["away_score"] = df["away_score"].clip(upper=GOAL_CAP)
    return df.reset_index(drop=True), as_of

# -----------------------------------------------------------------------------
# 4. ELO -- computed on the same competitive set. Returns ratings as of `as_of`.
#    Used as (a) the prior target for Dixon-Coles and (b) a backtest baseline.
# -----------------------------------------------------------------------------
def compute_elo(df):
    ratings = {}
    def get(t): return ratings.get(t, 1500.0)
    for r in df.sort_values("date").itertuples(index=False):
        rh, ra = get(r.home_team), get(r.away_team)
        hfa = 0.0 if r.neutral else HFA_ELO
        exp_h = 1.0 / (1.0 + 10 ** ((ra - rh - hfa) / 400.0))
        gd = abs(r.home_score - r.away_score)
        g = 1.0 if gd <= 1 else (1.5 if gd == 2 else (1.75 + (gd - 3) / 8.0))
        if r.home_score > r.away_score:   s = 1.0
        elif r.home_score < r.away_score: s = 0.0
        else:                             s = 0.5
        delta = ELO_K * r.phi * g * (s - exp_h)   # importance-weighted: friendlies nudge gently
        ratings[r.home_team] = rh + delta
        ratings[r.away_team] = ra - delta
    return ratings

# -----------------------------------------------------------------------------
# 5. WEIGHTED DIXON-COLES with Elo-prior penalty
# -----------------------------------------------------------------------------
def _tau_log(x, y, lam, mu, rho):
    """Vectorized log of the Dixon-Coles low-score correction."""
    t = np.ones_like(lam)
    m00 = (x == 0) & (y == 0); t[m00] = 1 - lam[m00] * mu[m00] * rho
    m01 = (x == 0) & (y == 1); t[m01] = 1 + lam[m01] * rho
    m10 = (x == 1) & (y == 0); t[m10] = 1 + mu[m10] * rho
    m11 = (x == 1) & (y == 1); t[m11] = 1 - rho
    return np.log(np.clip(t, 1e-10, None))

def fit_dixon_coles(df, elo_ratings, kappa=KAPPA, sigma_scale=SIGMA_SCALE):
    teams = sorted(set(df["home_team"]) | set(df["away_team"]))
    idx = {t: i for i, t in enumerate(teams)}
    n = len(teams)

    h_idx = df["home_team"].map(idx).to_numpy()
    a_idx = df["away_team"].map(idx).to_numpy()
    x = df["home_score"].to_numpy()
    y = df["away_score"].to_numpy()
    not_neutral = (~df["neutral"].astype(bool)).to_numpy().astype(float)
    w = df["w"].to_numpy()

    gx, gy = gammaln(x + 1), gammaln(y + 1)   # precompute log factorials

    # Elo prior target on the log-goal scale (centered z-scores of Elo)
    elo_vec = np.array([elo_ratings.get(t, 1500.0) for t in teams])
    z = (elo_vec - elo_vec.mean()) / (elo_vec.std() + 1e-9)
    sigma_target = z * sigma_scale            # mean ~0 -> a prior on RELATIVE strength

    def neg_loglik(params):
        a = params[:n]
        a = a - a.mean()                      # gauge fix: mean(attack)=0
        d = params[n:2 * n]
        h, rho = params[2 * n], params[2 * n + 1]

        log_lam = a[h_idx] - d[a_idx] + h * not_neutral
        log_mu  = a[a_idx] - d[h_idx]
        lam, mu = np.exp(log_lam), np.exp(log_mu)

        ll_h = x * log_lam - lam - gx
        ll_a = y * log_mu  - mu - gy
        ll   = w * (_tau_log(x, y, lam, mu, rho) + ll_h + ll_a)

        sigma = a + d
        sigma_dev = sigma - sigma.mean()
        penalty = kappa * np.sum((sigma_dev - sigma_target) ** 2)
        return -ll.sum() + penalty

    x0 = np.concatenate([np.zeros(n), np.zeros(n), [0.25, 0.0]])
    bounds = [(None, None)] * (2 * n) + [(-0.5, 1.0), RHO_BOUNDS]
    res = minimize(neg_loglik, x0, method="L-BFGS-B", bounds=bounds,
                   options={"maxiter": 400, "maxfun": 60000})

    a = res.x[:n]; a = a - a.mean()
    d = res.x[n:2 * n]
    h, rho = res.x[2 * n], res.x[2 * n + 1]
    ratings = pd.DataFrame({"team": teams, "attack": a, "defense": d,
                            "strength": a + d, "elo": elo_vec})
    ratings = ratings.sort_values("strength", ascending=False).reset_index(drop=True)
    params = {"idx": idx, "attack": a, "defense": d, "home": h, "rho": rho,
              "converged": res.success}
    return ratings, params

# -----------------------------------------------------------------------------
# 6. MATCH PREDICTOR
# -----------------------------------------------------------------------------
def expected_goals(params, home, away, neutral=True):
    idx, a, d = params["idx"], params["attack"], params["defense"]
    hi, ai = idx[home], idx[away]
    h = 0.0 if neutral else params["home"]
    lam = np.exp(a[hi] - d[ai] + h)
    mu  = np.exp(a[ai] - d[hi])
    return lam, mu

def scoreline_matrix(lam, mu, rho, max_goals=MAX_GOALS):
    gi = np.arange(max_goals + 1)
    M = np.outer(poisson.pmf(gi, lam), poisson.pmf(gi, mu))
    M[0, 0] *= 1 - lam * mu * rho
    M[0, 1] *= 1 + lam * rho
    M[1, 0] *= 1 + mu * rho
    M[1, 1] *= 1 - rho
    M = np.clip(M, 0, None)
    return M / M.sum()

def predict_match(params, home, away, neutral=True):
    lam, mu = expected_goals(params, home, away, neutral)
    M = scoreline_matrix(lam, mu, params["rho"])
    p_home = np.tril(M, -1).sum()   # home goals > away goals
    p_draw = np.trace(M)
    p_away = np.triu(M, 1).sum()
    i, j = np.unravel_index(M.argmax(), M.shape)
    return {"p_home": p_home, "p_draw": p_draw, "p_away": p_away,
            "exp_home_goals": lam, "exp_away_goals": mu,
            "most_likely_score": (int(i), int(j))}

# -----------------------------------------------------------------------------
# 7. SCORING HELPERS (for Part 2 backtesting; defined here so they live with
#    the model). RPS is the headline metric for ordinal 1X2 outcomes.
# -----------------------------------------------------------------------------
def rps(p_home, p_draw, p_away, outcome):
    """outcome in {'H','D','A'}. Order: H > D > A. Lower is better."""
    p = np.array([p_home, p_draw, p_away])
    e = {"H": [1, 0, 0], "D": [0, 1, 0], "A": [0, 0, 1]}[outcome]
    cp, ce = np.cumsum(p), np.cumsum(e)
    return 0.5 * np.sum((cp[:-1] - ce[:-1]) ** 2)

def log_loss_1x2(p_home, p_draw, p_away, outcome):
    p = {"H": p_home, "D": p_draw, "A": p_away}[outcome]
    return -np.log(max(p, 1e-12))

# -----------------------------------------------------------------------------
# 8. DEMO -- run the whole pipeline and sanity-check the output
# -----------------------------------------------------------------------------
def _part1_demo():
    df, as_of = load_and_prepare()
    print(f"Training on {len(df):,} competitive matches up to {as_of.date()}")
    print("Top competitions by weight share:")
    print(df.groupby("tournament")["w"].sum().sort_values(ascending=False).head(8))

    elo = compute_elo(df)
    ratings, params = fit_dixon_coles(df, elo)
    print(f"\nConverged: {params['converged']} | "
          f"home adv (log): {params['home']:.3f} | rho: {params['rho']:.3f}")
    print("\nTop 20 teams by fitted strength (attack + defense):")
    print(ratings.head(20).to_string(index=False))

    # sample prediction (change names to teams present in your data)
    for h, a in [("Brazil", "Argentina"), ("France", "England")]:
        if h in params["idx"] and a in params["idx"]:
            r = predict_match(params, h, a, neutral=True)
            print(f"\n{h} vs {a} (neutral): "
                  f"H {r['p_home']:.0%} / D {r['p_draw']:.0%} / A {r['p_away']:.0%} | "
                  f"xG {r['exp_home_goals']:.2f}-{r['exp_away_goals']:.2f} | "
                  f"likely {r['most_likely_score']}")



# =============================================================================
# 2026 FIFA World Cup model -- PART 2: Monte Carlo tournament engine
# -----------------------------------------------------------------------------
# Runs AFTER Part 1 in the same Colab session. It uses the fitted `params`
# object and the helper functions from Part 1 to simulate the full 48-team
# tournament many times and estimate each team's probability of reaching every
# stage and of winning the title.
#
# >>> In Colab: run the Part 1 cell first, then paste and run this cell. <<<
# =============================================================================


# Pull the pieces we need from Part 1. In a Colab session where Part 1 was run
# in a previous cell these names already exist; the import is a no-op fallback.

ET_FRACTION = 0.34   # extra time as a fraction of a full match (30 of ~88 mins)

# -----------------------------------------------------------------------------
# 2026 GROUP DRAW  (source: FIFA draw, 5 Dec 2025)
# !!! TWO THINGS YOU MUST DO BEFORE RUNNING ON REAL DATA:
#   1. Fill the three PLAYOFF_* placeholders with the actual qualified teams
#      (UEFA play-off B winner -> Group F; inter-confederation play-off winners
#      -> Groups I and K). Check the Wikipedia "2026 FIFA World Cup" page.
#   2. Make EVERY name here match the normalized names in your dataset. Likely
#      fixes to add to NAME_MAP in Part 1 (or change here):
#        "Korea Republic"->"South Korea", "Czechia"->"Czech Republic",
#        "Turkiye"/"Türkiye"->"Turkey", "Cote d'Ivoire"->"Ivory Coast",
#        "Cabo Verde"->"Cape Verde", "USA"/"United States" consistency.
#      The engine prints any team it can't find, so run it and fix what it lists.
# -----------------------------------------------------------------------------
GROUPS_2026 = {
    "A": ["Mexico", "South Africa", "South Korea", "Czech Republic"],
    "B": ["Canada", "Bosnia and Herzegovina", "Qatar", "Switzerland"],
    "C": ["Brazil", "Morocco", "Haiti", "Scotland"],
    "D": ["USA", "Paraguay", "Australia", "Turkey"],
    "E": ["Germany", "Curacao", "Ivory Coast", "Ecuador"],
    "F": ["Netherlands", "Japan", "Tunisia", "PLAYOFF_F"],
    "G": ["Belgium", "Egypt", "Iran", "New Zealand"],
    "H": ["Spain", "Cape Verde", "Uruguay", "Saudi Arabia"],
    "I": ["France", "Senegal", "Norway", "PLAYOFF_I"],
    "J": ["Argentina", "Algeria", "Austria", "Jordan"],
    "K": ["Portugal", "PLAYOFF_K", "Uzbekistan", "Colombia"],
    "L": ["England", "Croatia", "Ghana", "Panama"],
}
DEFAULT_HOSTS = {"USA", "Canada", "Mexico"}   # hosts get a home-advantage term
# A World Cup host plays in big, largely neutral stadiums, so they get only a
# FRACTION of the full fitted home edge -- and it compounds across a deep run,
# so keep this modest. Tune it against backtest_stages() (Qatar 2022, the host,
# exited in the group stage; Russia 2018 reached the quarter-finals).
HOST_ADVANTAGE_SCALE = 0.40

# -----------------------------------------------------------------------------
# RATINGS LOOKUP -- convert the fitted arrays to dicts and fill any team that
# the model never saw (debutant / name mismatch) with a weak fallback so the
# engine never crashes; it prints the list so you can fix names.
# -----------------------------------------------------------------------------
def build_engine_ratings(params, all_teams, hosts):
    idx = params["idx"]
    att = {t: params["attack"][i] for t, i in idx.items()}
    dff = {t: params["defense"][i] for t, i in idx.items()}
    # weak fallback = 10th percentile of fitted strength, split evenly
    a_fallback = np.percentile(list(att.values()), 10)
    d_fallback = np.percentile(list(dff.values()), 10)
    missing = [t for t in all_teams if t not in idx]
    for t in missing:
        att[t], dff[t] = a_fallback, d_fallback
    if missing:
        print("WARNING -- not found in fitted ratings (using weak fallback):")
        print("  ", missing)
        print("  Fix these via NAME_MAP / the group dict, then re-run.\n")
    return {"att": att, "def": dff, "home": params["home"], "rho": params["rho"],
            "hosts": set(hosts), "host_adv": params["home"] * HOST_ADVANTAGE_SCALE}

def team_lambdas(eng, t1, t2):
    """Expected goals for t1 and t2, applying host advantage where it applies."""
    adv = eng["host_adv"]
    adv1 = adv if (t1 in eng["hosts"] and t2 not in eng["hosts"]) else 0.0
    adv2 = adv if (t2 in eng["hosts"] and t1 not in eng["hosts"]) else 0.0
    lam1 = np.exp(eng["att"][t1] - eng["def"][t2] + adv1)
    lam2 = np.exp(eng["att"][t2] - eng["def"][t1] + adv2)
    return lam1, lam2

# -----------------------------------------------------------------------------
# SCORELINE SAMPLING -- precompute each fixture's full Dixon-Coles distribution
# once (memoized), then sampling a result is a single searchsorted.
# -----------------------------------------------------------------------------
def get_dist(eng, t1, t2, cache):
    key = (t1, t2)
    if key in cache:
        return cache[key]
    lam1, lam2 = team_lambdas(eng, t1, t2)
    M = scoreline_matrix(lam1, lam2, eng["rho"])     # axis0 = t1 goals, axis1 = t2 goals
    flat = M.ravel()
    cumsum = np.cumsum(flat)
    g1 = np.repeat(np.arange(M.shape[0]), M.shape[1])
    g2 = np.tile(np.arange(M.shape[1]), M.shape[0])
    cache[key] = (cumsum, g1, g2)
    return cache[key]

def sample_match(eng, t1, t2, cache):
    cumsum, g1, g2 = get_dist(eng, t1, t2, cache)
    i = np.searchsorted(cumsum, np.random.random() * cumsum[-1])
    return int(g1[i]), int(g2[i])

def play_knockout(eng, t1, t2, cache):
    g1, g2 = sample_match(eng, t1, t2, cache)
    if g1 != g2:
        return t1 if g1 > g2 else t2
    lam1, lam2 = team_lambdas(eng, t1, t2)            # extra time
    e1 = np.random.poisson(lam1 * ET_FRACTION)
    e2 = np.random.poisson(lam2 * ET_FRACTION)
    if e1 != e2:
        return t1 if e1 > e2 else t2
    return t1 if np.random.random() < 0.5 else t2     # penalties ~ coin flip

# -----------------------------------------------------------------------------
# GROUP STAGE + THIRD-PLACE RANKING
# Tiebreakers implemented: points, goal difference, goals for, then random
# ("drawing of lots"). Head-to-head and fair-play are omitted (documented).
# -----------------------------------------------------------------------------
def _key(rec):  # rec = (points, goal_diff, goals_for)
    return (rec[0], rec[1], rec[2], np.random.random())

def simulate_group(eng, teams, cache):
    pts = {t: 0 for t in teams}; gf = {t: 0 for t in teams}; ga = {t: 0 for t in teams}
    for i in range(len(teams)):
        for j in range(i + 1, len(teams)):
            t1, t2 = teams[i], teams[j]
            g1, g2 = sample_match(eng, t1, t2, cache)
            gf[t1] += g1; ga[t1] += g2; gf[t2] += g2; ga[t2] += g1
            if g1 > g2:   pts[t1] += 3
            elif g2 > g1: pts[t2] += 3
            else:         pts[t1] += 1; pts[t2] += 1
    rec = {t: (pts[t], gf[t] - ga[t], gf[t]) for t in teams}
    standings = sorted(teams, key=lambda t: _key(rec[t]), reverse=True)
    return standings, rec

# -----------------------------------------------------------------------------
# BRACKET -- seed the 32 qualifiers (winners > runners-up > thirds, then by
# record) and place them in a standard single-elimination bracket.
# NOTE: this is a strength-seeded approximation of FIFA's fixed positional
# template + 495-combination third-place matrix. It gets the bracket TOPOLOGY
# and seeding spirit right; to reproduce FIFA's exact R32 pairings, replace
# build_bracket() with the official mapping. The effect on title/stage
# probabilities is second-order (the strongest teams advance regardless of
# which specific slot they fill).
# -----------------------------------------------------------------------------
def _bracket_seed_positions(n):
    order = [0]
    while len(order) < n:
        size = len(order) * 2
        order = [x for pair in ((s, size - 1 - s) for s in order) for x in pair]
    return order

def build_bracket(qualifiers):
    # qualifiers: list of (team, tier, rec) ; tier 0=winner,1=runner-up,2=third
    seeded = sorted(qualifiers, key=lambda q: (q[1], -q[2][0], -q[2][1], -q[2][2]))
    teams_by_seed = [q[0] for q in seeded]
    return [teams_by_seed[p] for p in _bracket_seed_positions(len(teams_by_seed))]

# -----------------------------------------------------------------------------
# ONE TOURNAMENT
# -----------------------------------------------------------------------------
def simulate_tournament(eng, groups, cache):
    reached = {t: 0 for grp in groups.values() for t in grp}   # 0 = out in group
    winners, runners, thirds = [], [], []
    for g, teams in groups.items():
        standings, rec = simulate_group(eng, teams, cache)
        winners.append((standings[0], 0, rec[standings[0]]))
        runners.append((standings[1], 1, rec[standings[1]]))
        thirds.append((standings[2], 2, rec[standings[2]]))

    best_thirds = sorted(thirds, key=lambda q: _key(q[2]), reverse=True)[:8]
    qualifiers = winners + runners + best_thirds
    for t, _, _ in qualifiers:
        reached[t] = 1                                          # reached R32

    bracket = build_bracket(qualifiers)
    round_teams, reward = bracket, 2
    while len(round_teams) > 1:
        nxt = []
        for k in range(0, len(round_teams), 2):
            w = play_knockout(eng, round_teams[k], round_teams[k + 1], cache)
            reached[w] = reward
            nxt.append(w)
        round_teams, reward = nxt, reward + 1
    return reached  # values: 0 grp, 1 R32, 2 R16, 3 QF, 4 SF, 5 Final, 6 Champion

# -----------------------------------------------------------------------------
# MONTE CARLO
# -----------------------------------------------------------------------------
def run_monte_carlo(params, groups=GROUPS_2026, hosts=DEFAULT_HOSTS, n=20000, seed=0):
    np.random.seed(seed)
    all_teams = [t for grp in groups.values() for t in grp]
    eng = build_engine_ratings(params, all_teams, hosts)
    cache = {}
    counts = {t: np.zeros(7, dtype=np.int64) for t in all_teams}  # index = stage reached
    for _ in range(n):
        reached = simulate_tournament(eng, groups, cache)
        for t, r in reached.items():
            counts[t][r] += 1

    rows = []
    for t in all_teams:
        c = counts[t]
        # P(reach AT LEAST stage s) = cumulative from the top
        p_r32   = c[1:].sum() / n
        p_r16   = c[2:].sum() / n
        p_qf    = c[3:].sum() / n
        p_sf    = c[4:].sum() / n
        p_final = c[5:].sum() / n
        p_win   = c[6]        / n
        rows.append((t, p_win, p_final, p_sf, p_qf, p_r16, p_r32))
    df = pd.DataFrame(rows, columns=["team", "win", "final", "semi",
                                     "quarter", "r16", "qualify"])
    return df.sort_values("win", ascending=False).reset_index(drop=True)

def forecast_2026(params):
    res = run_monte_carlo(params, n=20000)
    pd.options.display.float_format = lambda x: f"{x:6.1%}"
    print("\n2026 World Cup -- title & stage probabilities (top 15):\n")
    print(res.head(15).to_string(index=False))
    print(f"\nTitle probability sums to {res['win'].sum():.3f} (should be ~1.0)")
    return res




# =============================================================================
# 2026 FIFA World Cup model -- PART 3: backtesting harness (match level)
# -----------------------------------------------------------------------------
# Validates the model by replaying the 2018 and 2022 World Cups: it fits the
# model using ONLY data before each kickoff, predicts the actual matches (which
# already live in results.csv), and scores those probabilities with proper
# metrics against two baselines. This is what tells you whether the model is
# any good -- and whether a hyperparameter like FRIENDLY_WEIGHT is well chosen.
#
# >>> In Colab: run the Part 1 cell first, then this cell, then: main() <<<
#
# NOTE: the bracket/stage-level calibration (P(reach QF) etc.) is a separate
# add-on because it needs the historical group draws transcribed; this file
# covers the match-level evaluation, which needs nothing but results.csv.
# =============================================================================



# World Cup kickoff dates -- the strict as-of cutoff for each backtest.
KICKOFF = {2018: pd.Timestamp("2018-06-14"),
           2022: pd.Timestamp("2022-11-20")}

# A neutral-venue base-rate prior (the floor baseline). Home/draw/away.
BASE_RATE = (0.40, 0.28, 0.32)

# -----------------------------------------------------------------------------
# FIT AS OF a date -- everything routes through here so no future data leaks.
# -----------------------------------------------------------------------------
def fit_as_of(date):
    df, as_of = load_and_prepare(as_of=date)
    elo = compute_elo(df)
    _, params = fit_dixon_coles(df, elo)
    return params, elo

# -----------------------------------------------------------------------------
# ACTUAL World Cup matches for a year (pulled straight from results.csv).
# Recorded scores are full-time (90'), so shootout results count as draws --
# which is correct, since the model predicts the 90-minute outcome.
# -----------------------------------------------------------------------------
def get_wc_matches(year, path=None):
    path = path or RESULTS_PATH
    df = pd.read_csv(path, parse_dates=["date"])
    df = normalize_names(df)
    df = df[(df["tournament"] == "FIFA World Cup") & (df["date"].dt.year == year)]
    df = df.dropna(subset=["home_score", "away_score"]).copy()
    return df.reset_index(drop=True)

def outcome(hs, ascore):
    return "H" if hs > ascore else ("A" if ascore > hs else "D")

# -----------------------------------------------------------------------------
# BASELINE: Elo -> 1X2.  Expected score from the Elo gap, a fixed draw band,
# and the rest split by that expected score. Simple and standard.
# -----------------------------------------------------------------------------
def elo_1x2(elo, home, away, neutral, base_draw=0.26):
    rh, ra = elo.get(home, 1500.0), elo.get(away, 1500.0)
    hfa = 0.0 if neutral else HFA_ELO
    E = 1.0 / (1.0 + 10 ** ((ra - rh - hfa) / 400.0))   # expected score for home
    return ((1 - base_draw) * E, base_draw, (1 - base_draw) * (1 - E))

# -----------------------------------------------------------------------------
# SCORE one tournament: model vs Elo-only vs base-rate, with RPS, log-loss,
# and a pooled calibration error.
# -----------------------------------------------------------------------------
def score_tournament(year, kickoff=None, verbose=True):
    cutoff = kickoff or KICKOFF[year]
    params, elo = fit_as_of(cutoff)
    matches = get_wc_matches(year)

    acc = {m: {"rps": [], "ll": []} for m in ("model", "elo", "base")}
    cal = []   # (predicted_prob, hit) pooled over the 3 classes, model only
    skipped = 0
    for r in matches.itertuples(index=False):
        h, a, neu = r.home_team, r.away_team, bool(r.neutral)
        if h not in params["idx"] or a not in params["idx"]:
            skipped += 1
            continue
        o = outcome(r.home_score, r.away_score)

        pr = predict_match(params, h, a, neutral=neu)
        probs = {
            "model": (pr["p_home"], pr["p_draw"], pr["p_away"]),
            "elo":   elo_1x2(elo, h, a, neu),
            "base":  BASE_RATE,
        }
        for name, p in probs.items():
            acc[name]["rps"].append(rps(*p, o))
            acc[name]["ll"].append(log_loss_1x2(*p, o))
        e = {"H": [1, 0, 0], "D": [0, 1, 0], "A": [0, 0, 1]}[o]
        for k in range(3):
            cal.append((probs["model"][k], e[k]))

    summary = pd.DataFrame({
        name: {"RPS": np.mean(v["rps"]), "LogLoss": np.mean(v["ll"])}
        for name, v in acc.items()
    }).T[["RPS", "LogLoss"]]

    ece = _expected_calibration_error(cal)
    if verbose:
        n = len(acc["model"]["rps"])
        print(f"\n=== {year} World Cup backtest (fit as of {cutoff.date()}, "
              f"{n} matches, {skipped} skipped) ===")
        print(summary.to_string(float_format=lambda x: f"{x:.4f}"))
        print(f"model calibration error (ECE): {ece:.3f}   (lower = better)")
        better = summary.loc["model", "RPS"] < summary.loc["elo", "RPS"]
        print("--> model "
              + ("BEATS" if better else "does NOT beat")
              + " the Elo baseline on RPS")
    return summary, ece

def _expected_calibration_error(pairs, bins=10):
    p = np.array([x[0] for x in pairs]); y = np.array([x[1] for x in pairs])
    edges = np.linspace(0, 1, bins + 1)
    ece, n = 0.0, len(p)
    for b in range(bins):
        m = (p >= edges[b]) & (p < edges[b + 1] if b < bins - 1 else p <= edges[b + 1])
        if m.sum():
            ece += (m.sum() / n) * abs(p[m].mean() - y[m].mean())
    return ece

# -----------------------------------------------------------------------------
# HYPERPARAMETER TUNING (e.g. FRIENDLY_WEIGHT).  IMPORTANT: tune on ONE
# tournament, then report final numbers on the OTHER, untouched one -- never
# pick a value using the same World Cup you quote results on.
# -----------------------------------------------------------------------------
def sweep_friendly_weight(tune_year, values=(0.0, 0.1, 0.2, 0.35, 0.5)):
    print(f"Tuning FRIENDLY_WEIGHT on the {tune_year} World Cup "
          f"(do NOT also report on {tune_year}):")
    original = FRIENDLY_WEIGHT
    out = []
    for v in values:
        FRIENDLY_WEIGHT = v
        summ, _ = score_tournament(tune_year, verbose=False)
        out.append((v, summ.loc["model", "RPS"], summ.loc["model", "LogLoss"]))
        print(f"  FRIENDLY_WEIGHT={v:<4}  RPS={out[-1][1]:.4f}  LogLoss={out[-1][2]:.4f}")
    FRIENDLY_WEIGHT = original
    best = min(out, key=lambda r: r[1])
    print(f"  best by RPS: FRIENDLY_WEIGHT={best[0]}")
    return out

def backtest_matches():
    for yr in (2018, 2022):
        score_tournament(yr)
    print("\nRule of thumb: the model should beat base-rate comfortably and "
          "land near (not necessarily beat) Elo. If it trails Elo, revisit "
          "FRIENDLY_WEIGHT / KAPPA via sweep_friendly_weight() on ONE year.")




# =============================================================================
# 2026 FIFA World Cup model -- PART 3b: stage-level calibration (engine check)
# -----------------------------------------------------------------------------
# Part 3 validated the MATCH model. This validates the SIMULATION ENGINE: it
# replays the 2018 and 2022 World Cups in their 32-team / Round-of-16 format,
# estimates each team's probability of reaching every stage, and checks those
# probabilities against what actually happened. With ~64 teams x 5 stage
# thresholds pooled across both tournaments, you get enough (predicted, actual)
# points for a genuine calibration curve on the engine itself.
#
# >>> In Colab: run Part 1, Part 2, and Part 3 cells first, then this. <<<
# It auto-runs main() at the bottom.
#
# Double-check the two group draws below against Wikipedia, and make the names
# match your dataset's normalized names (the engine prints any it can't find).
# =============================================================================


# ---- historical group draws (top 2 per group advance; no third-place slots) --
GROUPS_2018 = {
    "A": ["Russia", "Saudi Arabia", "Egypt", "Uruguay"],
    "B": ["Portugal", "Spain", "Morocco", "Iran"],
    "C": ["France", "Australia", "Peru", "Denmark"],
    "D": ["Argentina", "Iceland", "Croatia", "Nigeria"],
    "E": ["Brazil", "Switzerland", "Costa Rica", "Serbia"],
    "F": ["Germany", "Mexico", "Sweden", "South Korea"],
    "G": ["Belgium", "Panama", "Tunisia", "England"],
    "H": ["Poland", "Senegal", "Colombia", "Japan"],
}
GROUPS_2022 = {
    "A": ["Qatar", "Ecuador", "Senegal", "Netherlands"],
    "B": ["England", "Iran", "USA", "Wales"],
    "C": ["Argentina", "Saudi Arabia", "Mexico", "Poland"],
    "D": ["France", "Australia", "Denmark", "Tunisia"],
    "E": ["Spain", "Costa Rica", "Germany", "Japan"],
    "F": ["Belgium", "Canada", "Morocco", "Croatia"],
    "G": ["Brazil", "Serbia", "Switzerland", "Cameroon"],
    "H": ["Portugal", "Ghana", "Uruguay", "South Korea"],
}
HOST = {2018: "Russia", 2022: "Qatar"}

# ---- actual furthest stage reached: 0 group, 1 R16, 2 QF, 3 SF, 4 Final, 5 Champion
ACTUAL_2018 = {
    "France": 5, "Croatia": 4, "Belgium": 3, "England": 3,
    "Uruguay": 2, "Russia": 2, "Brazil": 2, "Sweden": 2,
    "Argentina": 1, "Portugal": 1, "Spain": 1, "Denmark": 1,
    "Mexico": 1, "Japan": 1, "Switzerland": 1, "Colombia": 1,
    "Saudi Arabia": 0, "Egypt": 0, "Morocco": 0, "Iran": 0, "Australia": 0,
    "Peru": 0, "Iceland": 0, "Nigeria": 0, "Costa Rica": 0, "Serbia": 0,
    "Germany": 0, "South Korea": 0, "Panama": 0, "Tunisia": 0, "Poland": 0,
    "Senegal": 0,
}
ACTUAL_2022 = {
    "Argentina": 5, "France": 4, "Croatia": 3, "Morocco": 3,
    "Netherlands": 2, "Brazil": 2, "England": 2, "Portugal": 2,
    "USA": 1, "Australia": 1, "Poland": 1, "Senegal": 1,
    "Japan": 1, "South Korea": 1, "Spain": 1, "Switzerland": 1,
    "Qatar": 0, "Ecuador": 0, "Iran": 0, "Wales": 0, "Saudi Arabia": 0,
    "Mexico": 0, "Denmark": 0, "Tunisia": 0, "Costa Rica": 0, "Germany": 0,
    "Belgium": 0, "Canada": 0, "Serbia": 0, "Cameroon": 0, "Ghana": 0,
    "Uruguay": 0,
}
STAGE_NAMES = ["R16", "QF", "SF", "Final", "Champion"]   # thresholds 1..5

# -----------------------------------------------------------------------------
# 32-team tournament (top 2 advance, no thirds) -- reuses Part 2's primitives.
# -----------------------------------------------------------------------------
def _simulate_32(eng, groups, cache):
    reached = {t: 0 for g in groups.values() for t in g}
    winners, runners = [], []
    for g, teams in groups.items():
        standings, rec = simulate_group(eng, teams, cache)
        winners.append((standings[0], 0, rec[standings[0]]))
        runners.append((standings[1], 1, rec[standings[1]]))
    qualifiers = winners + runners            # 16 teams, no third-place slots
    for t, _, _ in qualifiers:
        reached[t] = 1
    bracket, reward = build_bracket(qualifiers), 2
    while len(bracket) > 1:
        nxt = []
        for k in range(0, len(bracket), 2):
            w = play_knockout(eng, bracket[k], bracket[k + 1], cache)
            reached[w] = reward; nxt.append(w)
        bracket, reward = nxt, reward + 1
    return reached                            # values 0..5

def run_mc_historical(params, groups, host, n=10000, seed=0):
    np.random.seed(seed)
    all_teams = [t for g in groups.values() for t in g]
    eng = build_engine_ratings(params, all_teams, {host})
    cache = {}
    counts = {t: np.zeros(6, dtype=np.int64) for t in all_teams}
    for _ in range(n):
        for t, r in _simulate_32(eng, groups, cache).items():
            counts[t][r] += 1
    rows = []
    for t in all_teams:
        c = counts[t]
        rows.append((t, c[1:].sum()/n, c[2:].sum()/n, c[3:].sum()/n,
                     c[4:].sum()/n, c[5]/n))            # P(>=R16,QF,SF,Final,Champ)
    return pd.DataFrame(rows, columns=["team"] + STAGE_NAMES)

# -----------------------------------------------------------------------------
# BACKTEST a year: predicted stage probs vs actual, plus champion rank.
# -----------------------------------------------------------------------------
def backtest_year(year, n=10000):
    params, _ = fit_as_of(KICKOFF[year])
    groups = GROUPS_2018 if year == 2018 else GROUPS_2022
    actual = ACTUAL_2018 if year == 2018 else ACTUAL_2022
    pred = run_mc_historical(params, groups, HOST[year], n=n)

    champ = max(actual, key=actual.get)
    rank = pred.sort_values("Champion", ascending=False).reset_index(drop=True)
    champ_rank = rank.index[rank["team"] == champ][0] + 1
    champ_prob = float(rank.loc[rank["team"] == champ, "Champion"].iloc[0])
    print(f"\n{year}: actual champion {champ} was ranked #{champ_rank} "
          f"in predicted title probability ({champ_prob:.1%}).")
    print(f"  predicted top 4: "
          f"{', '.join(rank['team'].head(4) + ' ' + (rank['Champion'].head(4)*100).round(1).astype(str) + '%')}")

    # collect pooled (predicted, actual) over the 5 stage thresholds
    points = []
    for _, row in pred.iterrows():
        a = actual.get(row["team"], 0)
        for k, name in enumerate(STAGE_NAMES, start=1):
            points.append((row[name], 1 if a >= k else 0))
    return points

# -----------------------------------------------------------------------------
# CALIBRATION over the pooled (predicted, actual) points from both years.
# -----------------------------------------------------------------------------
def calibration_report(points, bins=5):
    p = np.array([x[0] for x in points]); y = np.array([x[1] for x in points])
    brier = np.mean((p - y) ** 2)
    edges = np.linspace(0, 1, bins + 1)
    print("\n--- engine calibration (pooled 2018 + 2022, team x stage events) ---")
    print(f"{'predicted band':>16} | {'n':>4} | {'mean pred':>9} | {'actual freq':>11}")
    ece = 0.0
    for b in range(bins):
        hi = p <= edges[b+1] if b == bins-1 else p < edges[b+1]
        m = (p >= edges[b]) & hi
        if m.sum():
            ece += (m.sum()/len(p)) * abs(p[m].mean() - y[m].mean())
            print(f"  {edges[b]:.1f}-{edges[b+1]:.1f}      | {m.sum():>4} | "
                  f"{p[m].mean():>9.2f} | {y[m].mean():>11.2f}")
    print(f"\nBrier score: {brier:.4f}   ECE: {ece:.3f}   (both lower = better)")
    print("Well calibrated => 'mean pred' ~ 'actual freq' in every band.")

def backtest_stages(n=10000):
    pts = []
    for yr in (2018, 2022):
        pts += backtest_year(yr, n=n)
    calibration_report(pts)



# =============================================================================
# DRIVER -- runs when you execute this file / paste it into a Colab cell.
# =============================================================================
def fit_current(verbose=True):
    data, as_of = load_and_prepare()
    elo = compute_elo(data)
    ratings, params = fit_dixon_coles(data, elo)
    if verbose:
        print(f"Trained on {len(data):,} competitive matches up to {as_of.date()}")
        print("\nTop 20 by fitted strength:")
        print(ratings.head(20).to_string(index=False))
    return ratings, params

def run_all():
    print("Fitting the ratings model ...")
    ratings, params = fit_current()
    print("\nSimulating the 2026 World Cup (20,000 runs) ...")
    forecast_2026(params)
    print("\n--- optional validation (each refits the model, a few minutes) ---")
    print("  backtest_matches()   # match-level RPS / log-loss vs Elo & base rate")
    print("  backtest_stages()    # stage-level calibration on 2018 & 2022")
    return ratings, params

if __name__ == "__main__":
    ratings, params = run_all()

import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap

def plot_stage_heatmap(res, top_n=16, save_path=None):
    res = res.sort_values("win", ascending=False).head(top_n)
    cols = ["qualify", "r16", "quarter", "semi", "final", "win"]
    labels = ["Reach\nR32", "Reach\nR16", "Reach\nQF", "Reach\nSF", "Reach\nFinal", "Champion"]
    M = res[cols].to_numpy()
    if M.max() <= 1.01:
        M = M * 100
    cmap = LinearSegmentedColormap.from_list("wc", ["#0d1b2a", "#1b4965", "#5fa8d3", "#cae9ff"])
    fig, ax = plt.subplots(figsize=(8.5, 0.46 * len(res) + 1.4))
    im = ax.imshow(M, cmap=cmap, aspect="auto", vmin=0, vmax=100)
    ax.set_xticks(range(len(labels)))
    ax.set_xticklabels(labels, fontsize=9)
    ax.set_yticks(range(len(res)))
    ax.set_yticklabels(res["team"], fontsize=9)
    ax.xaxis.set_ticks_position("top")
    ax.tick_params(length=0)
    for s in ax.spines.values():
        s.set_visible(False)
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            v = M[i, j]
            ax.text(j, i, f"{v:.0f}%", ha="center", va="center", fontsize=8.5,
                    color="white" if v < 55 else "#0d1b2a",
                    fontweight="bold" if cols[j] == "win" else "normal")
    ax.set_title("2026 World Cup — probability of reaching each stage",
                 fontsize=12, fontweight="bold", pad=26, loc="left")
    fig.colorbar(im, ax=ax, fraction=0.025, pad=0.02).set_label("probability (%)", fontsize=8)
    plt.tight_layout()
    if save_path:
        fig.savefig(save_path, dpi=150, bbox_inches="tight")
    return fig

res = run_monte_carlo(params)
plot_stage_heatmap(res)

# Match-level backtest: RPS / log-loss vs Elo and base-rate baselines
backtest_matches()

# Stage-level backtest: did the right teams reach the right rounds?
backtest_stages()